/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as authRouteRouteImport } from './../pages/(auth)/route'
import { Route as appRouteRouteImport } from './../pages/(app)/route'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as authLoginIndexRouteImport } from './../pages/(auth)/login/index'
import { Route as appSupportIndexRouteImport } from './../pages/(app)/support/index'
import { Route as appSettingsIndexRouteImport } from './../pages/(app)/settings/index'
import { Route as appJobsIndexRouteImport } from './../pages/(app)/jobs/index'
import { Route as appFinanceIndexRouteImport } from './../pages/(app)/finance/index'
import { Route as appCompaniesIndexRouteImport } from './../pages/(app)/companies/index'
import { Route as authLoginVerifyRouteImport } from './../pages/(auth)/login/verify'
import { Route as appCompaniesIdRouteImport } from './../pages/(app)/companies/$id'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const appSupportIndexRoute = appSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)
const appJobsIndexRoute = appJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appFinanceIndexRoute = appFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompaniesIndexRoute = appCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginVerifyRoute = authLoginVerifyRouteImport.update({
  id: '/login/verify',
  path: '/login/verify',
  getParentRoute: () => authRouteRoute,
} as any)
const appCompaniesIdRoute = appCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$id': typeof appCompaniesIdRoute
  '/login/verify': typeof authLoginVerifyRoute
  '/companies/': typeof appCompaniesIndexRoute
  '/finance/': typeof appFinanceIndexRoute
  '/jobs/': typeof appJobsIndexRoute
  '/settings/': typeof appSettingsIndexRoute
  '/support/': typeof appSupportIndexRoute
  '/login/': typeof authLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$id': typeof appCompaniesIdRoute
  '/login/verify': typeof authLoginVerifyRoute
  '/companies': typeof appCompaniesIndexRoute
  '/finance': typeof appFinanceIndexRoute
  '/jobs': typeof appJobsIndexRoute
  '/settings': typeof appSettingsIndexRoute
  '/support': typeof appSupportIndexRoute
  '/login': typeof authLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/companies/$id': typeof appCompaniesIdRoute
  '/(auth)/login/verify': typeof authLoginVerifyRoute
  '/(app)/companies/': typeof appCompaniesIndexRoute
  '/(app)/finance/': typeof appFinanceIndexRoute
  '/(app)/jobs/': typeof appJobsIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(app)/support/': typeof appSupportIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies/$id'
    | '/login/verify'
    | '/companies/'
    | '/finance/'
    | '/jobs/'
    | '/settings/'
    | '/support/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies/$id'
    | '/login/verify'
    | '/companies'
    | '/finance'
    | '/jobs'
    | '/settings'
    | '/support'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/companies/$id'
    | '/(auth)/login/verify'
    | '/(app)/companies/'
    | '/(app)/finance/'
    | '/(app)/jobs/'
    | '/(app)/settings/'
    | '/(app)/support/'
    | '/(auth)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/support/': {
      id: '/(app)/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof appSupportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/jobs/': {
      id: '/(app)/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof appJobsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/finance/': {
      id: '/(app)/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof appFinanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/companies/': {
      id: '/(app)/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof appCompaniesIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login/verify': {
      id: '/(auth)/login/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof authLoginVerifyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/companies/$id': {
      id: '/(app)/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof appCompaniesIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appCompaniesIdRoute: typeof appCompaniesIdRoute
  appCompaniesIndexRoute: typeof appCompaniesIndexRoute
  appFinanceIndexRoute: typeof appFinanceIndexRoute
  appJobsIndexRoute: typeof appJobsIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
  appSupportIndexRoute: typeof appSupportIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appCompaniesIdRoute: appCompaniesIdRoute,
  appCompaniesIndexRoute: appCompaniesIndexRoute,
  appFinanceIndexRoute: appFinanceIndexRoute,
  appJobsIndexRoute: appJobsIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
  appSupportIndexRoute: appSupportIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginVerifyRoute: typeof authLoginVerifyRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginVerifyRoute: authLoginVerifyRoute,
  authLoginIndexRoute: authLoginIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
