/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as authRouteRouteImport } from './../pages/(auth)/route'
import { Route as appRouteRouteImport } from './../pages/(app)/route'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as appProfileRouteRouteImport } from './../pages/(app)/profile/route'
import { Route as authForgotIndexRouteImport } from './../pages/(auth)/forgot/index'
import { Route as appProfileIndexRouteImport } from './../pages/(app)/profile/index'
import { Route as appMyIndexRouteImport } from './../pages/(app)/my/index'
import { Route as appJobsIndexRouteImport } from './../pages/(app)/jobs/index'
import { Route as appDashboardIndexRouteImport } from './../pages/(app)/dashboard/index'
import { Route as appClaimedIndexRouteImport } from './../pages/(app)/claimed/index'
import { Route as appChatIndexRouteImport } from './../pages/(app)/chat/index'
import { Route as appChatIdRouteImport } from './../pages/(app)/chat/$id'
import { Route as appProfileVerificationIndexRouteImport } from './../pages/(app)/profile/verification/index'
import { Route as appProfileSecurityIndexRouteImport } from './../pages/(app)/profile/security/index'
import { Route as appProfilePaymentIndexRouteImport } from './../pages/(app)/profile/payment/index'
import { Route as appProfileNotificationsIndexRouteImport } from './../pages/(app)/profile/notifications/index'
import { Route as appProfileFleetIndexRouteImport } from './../pages/(app)/profile/fleet/index'
import { Route as appProfileCompanyIndexRouteImport } from './../pages/(app)/profile/company/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const authForgotIndexRoute = authForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => authRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appMyIndexRoute = appMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => appRouteRoute,
} as any)
const appJobsIndexRoute = appJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)
const appClaimedIndexRoute = appClaimedIndexRouteImport.update({
  id: '/claimed/',
  path: '/claimed/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => appRouteRoute,
} as any)
const appChatIdRoute = appChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileVerificationIndexRoute =
  appProfileVerificationIndexRouteImport.update({
    id: '/verification/',
    path: '/verification/',
    getParentRoute: () => appProfileRouteRoute,
  } as any)
const appProfileSecurityIndexRoute = appProfileSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appProfilePaymentIndexRoute = appProfilePaymentIndexRouteImport.update({
  id: '/payment/',
  path: '/payment/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appProfileNotificationsIndexRoute =
  appProfileNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => appProfileRouteRoute,
  } as any)
const appProfileFleetIndexRoute = appProfileFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appProfileCompanyIndexRoute = appProfileCompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => appProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof appProfileRouteRouteWithChildren
  '/chat/$id': typeof appChatIdRoute
  '/chat': typeof appChatIndexRoute
  '/claimed': typeof appClaimedIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/jobs': typeof appJobsIndexRoute
  '/my': typeof appMyIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/forgot': typeof authForgotIndexRoute
  '/profile/company': typeof appProfileCompanyIndexRoute
  '/profile/fleet': typeof appProfileFleetIndexRoute
  '/profile/notifications': typeof appProfileNotificationsIndexRoute
  '/profile/payment': typeof appProfilePaymentIndexRoute
  '/profile/security': typeof appProfileSecurityIndexRoute
  '/profile/verification': typeof appProfileVerificationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$id': typeof appChatIdRoute
  '/chat': typeof appChatIndexRoute
  '/claimed': typeof appClaimedIndexRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/jobs': typeof appJobsIndexRoute
  '/my': typeof appMyIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/forgot': typeof authForgotIndexRoute
  '/profile/company': typeof appProfileCompanyIndexRoute
  '/profile/fleet': typeof appProfileFleetIndexRoute
  '/profile/notifications': typeof appProfileNotificationsIndexRoute
  '/profile/payment': typeof appProfilePaymentIndexRoute
  '/profile/security': typeof appProfileSecurityIndexRoute
  '/profile/verification': typeof appProfileVerificationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteRouteWithChildren
  '/(app)/chat/$id': typeof appChatIdRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/claimed/': typeof appClaimedIndexRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/jobs/': typeof appJobsIndexRoute
  '/(app)/my/': typeof appMyIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(auth)/forgot/': typeof authForgotIndexRoute
  '/(app)/profile/company/': typeof appProfileCompanyIndexRoute
  '/(app)/profile/fleet/': typeof appProfileFleetIndexRoute
  '/(app)/profile/notifications/': typeof appProfileNotificationsIndexRoute
  '/(app)/profile/payment/': typeof appProfilePaymentIndexRoute
  '/(app)/profile/security/': typeof appProfileSecurityIndexRoute
  '/(app)/profile/verification/': typeof appProfileVerificationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/chat/$id'
    | '/chat'
    | '/claimed'
    | '/dashboard'
    | '/jobs'
    | '/my'
    | '/profile/'
    | '/forgot'
    | '/profile/company'
    | '/profile/fleet'
    | '/profile/notifications'
    | '/profile/payment'
    | '/profile/security'
    | '/profile/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat/$id'
    | '/chat'
    | '/claimed'
    | '/dashboard'
    | '/jobs'
    | '/my'
    | '/profile'
    | '/forgot'
    | '/profile/company'
    | '/profile/fleet'
    | '/profile/notifications'
    | '/profile/payment'
    | '/profile/security'
    | '/profile/verification'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/profile'
    | '/(app)/chat/$id'
    | '/(app)/chat/'
    | '/(app)/claimed/'
    | '/(app)/dashboard/'
    | '/(app)/jobs/'
    | '/(app)/my/'
    | '/(app)/profile/'
    | '/(auth)/forgot/'
    | '/(app)/profile/company/'
    | '/(app)/profile/fleet/'
    | '/(app)/profile/notifications/'
    | '/(app)/profile/payment/'
    | '/(app)/profile/security/'
    | '/(app)/profile/verification/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/forgot/': {
      id: '/(auth)/forgot/'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof authForgotIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/my/': {
      id: '/(app)/my/'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof appMyIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/jobs/': {
      id: '/(app)/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof appJobsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/claimed/': {
      id: '/(app)/claimed/'
      path: '/claimed'
      fullPath: '/claimed'
      preLoaderRoute: typeof appClaimedIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/chat/$id': {
      id: '/(app)/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof appChatIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile/verification/': {
      id: '/(app)/profile/verification/'
      path: '/verification'
      fullPath: '/profile/verification'
      preLoaderRoute: typeof appProfileVerificationIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/profile/security/': {
      id: '/(app)/profile/security/'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof appProfileSecurityIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/profile/payment/': {
      id: '/(app)/profile/payment/'
      path: '/payment'
      fullPath: '/profile/payment'
      preLoaderRoute: typeof appProfilePaymentIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/profile/notifications/': {
      id: '/(app)/profile/notifications/'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof appProfileNotificationsIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/profile/fleet/': {
      id: '/(app)/profile/fleet/'
      path: '/fleet'
      fullPath: '/profile/fleet'
      preLoaderRoute: typeof appProfileFleetIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/profile/company/': {
      id: '/(app)/profile/company/'
      path: '/company'
      fullPath: '/profile/company'
      preLoaderRoute: typeof appProfileCompanyIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
  }
}

interface appProfileRouteRouteChildren {
  appProfileIndexRoute: typeof appProfileIndexRoute
  appProfileCompanyIndexRoute: typeof appProfileCompanyIndexRoute
  appProfileFleetIndexRoute: typeof appProfileFleetIndexRoute
  appProfileNotificationsIndexRoute: typeof appProfileNotificationsIndexRoute
  appProfilePaymentIndexRoute: typeof appProfilePaymentIndexRoute
  appProfileSecurityIndexRoute: typeof appProfileSecurityIndexRoute
  appProfileVerificationIndexRoute: typeof appProfileVerificationIndexRoute
}

const appProfileRouteRouteChildren: appProfileRouteRouteChildren = {
  appProfileIndexRoute: appProfileIndexRoute,
  appProfileCompanyIndexRoute: appProfileCompanyIndexRoute,
  appProfileFleetIndexRoute: appProfileFleetIndexRoute,
  appProfileNotificationsIndexRoute: appProfileNotificationsIndexRoute,
  appProfilePaymentIndexRoute: appProfilePaymentIndexRoute,
  appProfileSecurityIndexRoute: appProfileSecurityIndexRoute,
  appProfileVerificationIndexRoute: appProfileVerificationIndexRoute,
}

const appProfileRouteRouteWithChildren = appProfileRouteRoute._addFileChildren(
  appProfileRouteRouteChildren,
)

interface appRouteRouteChildren {
  appProfileRouteRoute: typeof appProfileRouteRouteWithChildren
  appChatIdRoute: typeof appChatIdRoute
  appChatIndexRoute: typeof appChatIndexRoute
  appClaimedIndexRoute: typeof appClaimedIndexRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appJobsIndexRoute: typeof appJobsIndexRoute
  appMyIndexRoute: typeof appMyIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appProfileRouteRoute: appProfileRouteRouteWithChildren,
  appChatIdRoute: appChatIdRoute,
  appChatIndexRoute: appChatIndexRoute,
  appClaimedIndexRoute: appClaimedIndexRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appJobsIndexRoute: appJobsIndexRoute,
  appMyIndexRoute: appMyIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotIndexRoute: typeof authForgotIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotIndexRoute: authForgotIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
